name: "terraform-deploy"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install dependencies and tests crawler
        run: |
          pip install -r requirements.txt -r requirements-test.txt
          python -m unittest discover -s tests/
          coverage run -m unittest discover -s tests/
          coverage report --include crawler/crawler.py
        working-directory: "./src/search_engine_crawler"
      - name: Install dependencies and tests ui
        run: |
          pip install -r requirements.txt -r requirements-test.txt
          python -m unittest discover -s tests/
          coverage run -m unittest discover -s tests/
          coverage report --include ui/ui.py
        working-directory: "./src/search_engine_ui"
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    env:
         TF_VAR_yc_token: ${{ secrets.YC_TOKEN }}
         TF_VAR_folder_id: ${{ secrets.FOLDER_ID }}
         TF_VAR_cloud_id: ${{ secrets.CLOUD_ID }}
         TF_VAR_basic_auth_pass: ${{ secrets.BASIC_AUTH_PASS }}
         TF_VAR_docker_username: ${{ secrets.DOCKER_USERNAME }}
         TF_VAR_docker_password: ${{ secrets.DOCKER_PASSWORD }}
         TF_VAR_rmq_username: ${{ secrets.RMQ_USERNAME }}
         TF_VAR_rmq_password: ${{ secrets.RMQ_PASSWORD }}
         TF_VAR_cluster_id: ${{ secrets.CLUSTER_ID }}
         ACCESS_KEY: ${{ secrets.ACCESS_KEY }}
         SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

        - name: Setup Terraform
        id: install_yc
        run: |
          curl https://storage.yandexcloud.net/yandexcloud-yc/install.sh | bash -s -- -h

      - name: Terraform Init Crawler
        id: init_crawler
        run: |
            rm -rf .terraform
            terraform init -backend-config="access_key=$ACCESS_KEY" -backend-config="secret_key=$SECRET_KEY"
        working-directory: "./terraform/app-crawler"

      - name: Terraform Plan Crawler
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color
        working-directory: "./terraform/app-crawler"

#      - name: Terraform Apply Crawler
#        id: apply
#        if: github.event_name == 'push'
#        run: terraform apply -auto-approve
#        working-directory: "./terraform/app-crawler"

