loki:
  replicas: 1

  persistence:
    enabled: true
    accessModes:
      - ReadWriteOnce
    size: 4Gi
    storageClassName: yc-network-ssd

  # https://grafana.com/docs/loki/latest/configuration/#configuring-grafana-loki
  config:
    # https://grafana.com/docs/loki/latest/operations/storage/wal/
    auth_enabled: false
    limits_config:
      retention_period: 744h
      max_query_length: 800h
    compactor:
      shared_store: filesystem
      compaction_interval: 10m
      retention_enabled: true
      retention_delete_delay: 2h
      retention_delete_worker_count: 150
      working_directory: /data/loki/boltdb-shipper-compactor
    # https://github.com/grafana/loki/blob/main/docs/sources/storage/_index.md#schema-configs
    # https://grafana.com/docs/loki/latest/operations/storage/schema/
    schema_config:
      configs:
        - from: 2022-10-29
          # https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper/
          store: boltdb-shipper
          object_store: filesystem
          schema: v11
          index:
            prefix: loki_index_
            period: 24h
    storage_config:
      boltdb_shipper:
        active_index_directory: /data/loki/boltdb-shipper-active
        cache_location: /data/loki/boltdb-shipper-cache
        cache_ttl: 24h
        shared_store: filesystem
      filesystem:
        directory: ${STORAGE_LOCAL_PATH}

promtail:
  enabled: true
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 128Mi

grafana:
  enabled: true
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 9.2.2